### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by mikemommsen** [elastic/homebrew-tap#123]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb:9

Warning: Tried to install empty array to /usr/local/etc/elasticsearch/jvm.options.d
==> codesign -f -s - /usr/local/Cellar/elasticsearch-full/7.15.2/libexec/modules/x-pack-ml/platform/darwin-x86_64/controller.app --deep
==> find /usr/local/Cellar/elasticsearch-full/7.15.2/libexec/jdk.app/Contents/Home/bin -type f -exec codesign -f -s - {} ;
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb:9

**Comment by mgreau** [comment]
Hi @mikemommsen 

Thanks for the report.

There is already a similar issue https://github.com/elastic/homebrew-tap/issues/110. 
Closing this one as a duplicate.

**Comment by mikemommsen** [comment]
thanks - i was able to solve it by following those steps
