### ISSUE TITLE
Can't install on MacOS 10.15

### ISSUE THREAD

**Issue by muhghazaliakbar** [elastic/homebrew-tap#14]
I have problem installing the package on MacOS catalina 10.15, anyone can help?

![Screen Shot 2019-09-25 at 13 40 33](https://user-images.githubusercontent.com/8321936/65572244-1910cd80-df9a-11e9-8976-fe2c32f8aad4.png)

**Comment by jasontedor** [comment]
@muhghazaliakbar I opened #15 to fix this. Can you test this on your Catalina installation? Here's how:

```
$ brew untap elastic/tap
$ brew tap jasontedor/tap
$ brew install elasticsearch-full
```

Installation should proceed now. Then we can integrate this and you should point back to the official Elastic tap:

```
$ brew untap jasontedor/tap
$ brew tap elastic/tap
```
