### ISSUE TITLE
Error in elasticsearch-full formula.

### ISSUE THREAD

**Issue by nataliaroncea12** [elastic/homebrew-tap#150]
I have a M1 Mac, and my elasticsearch-full stoped working. I tried to reinstall it but this is the error message i get 
```
Error: elasticsearch-full: Calling plist_options is disabled! Use service.require_root instead.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb:68
```
I have also tried to change the plist_options line with something the method "service" but it was also unsuccsesfull.
Can you please advise?

**Comment by kapilkaisare** [comment]
Seeing the same problem as well.

**Comment by marcosvcloures** [comment]
The actual folder for M1 Macs is

`cd /opt/homebrew/Library/Taps/elastic/homebrew-tap`

**Comment by Equationzhao** [comment]
+1

**Comment by GreatMuta514** [comment]
```
$ brew services start elasticsearch-full

Error: elasticsearch-full: undefined method `plist_options' for Formulary::FormulaNamespacefc8f134bd39648de0819bacf06d5db7a23dff2b46b56fa93160065443c96cc07::ElasticsearchFull:Class
```

**Comment by alexventuraio** [comment]
I'm getting the exact same error when trying to install it with brew:
```shell

> brew tap elastic/tap
==> Tapping elastic/tap
Cloning into '/opt/homebrew/Library/Taps/elastic/homebrew-tap'...
remote: Enumerating objects: 1407, done.
remote: Counting objects: 100% (586/586), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 1407 (delta 559), reused 530 (delta 521), pack-reused 821
Receiving objects: 100% (1407/1407), 328.79 KiB | 1.71 MiB/s, done.
Resolving deltas: 100% (1099/1099), done.
Tapped 17 formulae (38 files, 448.8KB).

> brew install elastic/tap/elasticsearch-full
Error: elastic/tap/elasticsearch-full: undefined method `plist_options' for Formulary::FormulaNamespacebf9a1382d41b546c07ca9fb03a7076777de36a194bc5d2ee6351261ec59a8ed3::ElasticsearchFull:Class
```

@GreatMuta514 Any progress on fixing it?

**Comment by alexventuraio** [comment]
> I'm getting the exact same error when trying to install it with brew:
> 
> Any progress on fixing it?

Ok, I did this to get it fixed and able to install ES 7 in Mac with M1 chip:

- Open the file with the class failing using your editor like this: `vim /opt/homebrew/Library/Taps/elastic/homebrew-tap/Formula/elasticsearch-full.rb`
- Replace the lines as per the opened PR [here](https://github.com/elastic/homebrew-tap/pull/144/files)
  ```ruby
  service do
    run [opt_bin/"elasticsearch"]
    working_dir var
    log_path var/"log/elasticsearch.log"
    error_log_path var/"log/elasticsearch.log"
  end
  ```
- Save the file and re-run the `brew install ...` command, you should be good now.

**Comment by RandomJo** [comment]
In addition following the lead of @todgru and @marcosvcloures, I also had to follow these instructions to get it fully working: [https://gist.github.com/todgru/0ba097d63318313f12a52594217f8e2b](https://gist.github.com/todgru/0ba097d63318313f12a52594217f8e2b)

**Comment by mgreau** [comment]
> Replace the lines as per the opened PR [here](https://github.com/elastic/homebrew-tap/pull/144/files)

The PR has been merged to fix this problem.
