### ISSUE TITLE
Warning: Calling depends_on :java is deprecated!

### ISSUE THREAD

**Issue by pulberg** [elastic/homebrew-tap#56]
From `brew` output - 

```
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/elastic/homebrew-tap/Formula/logstash-full.rb:7
```

**Comment by aarvee11** [comment]
Can we change the code to use openjdk instead of java anad raise a PR?

**Comment by pulberg** [comment]
@aarvee11 Not sure, which is why I didn't try that yet, was hoping someone from Elastic would comment.

**Comment by jsvd** [comment]
I'm not to familiar with taps but I noticed a few issues with logstash's. Pr #59 makes logstash rely on the jdk it ships with (like elasticsearch does), and also adds codesigning instruction (otherwise the bundled jdk can't be used).
Anyone willing to test this out?
